### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by benzmuircroft** [rtc-io/rtc-mesh#12]
If I visit https://switchboard.rtc.io/ in my browser I get 404 not found. But if I visit http://rtc.io/switchboard I first get 301 Moved Permanently then 404 not found straight after (In my networks tab in the chrome console).

Using https://github.com/rtc-io/rtc-mesh/blob/master/examples/crdt.js after building it with browserify i get:

```
WebSocket connection to 'ws://rtc.io/switchboard/' failed: Error during WebSocket handshake: Unexpected response code: 404
```

Happens with both addresses.

**Comment by benzmuircroft** [comment]
Created my own signalling server with rtc-switchboard and rtc-signaller, rtc-switchboard-messenger, freeice. Now it works!

**Comment by silviapfeiffer** [comment]
The 404 and 301 are to be expected, since they are not Web servers, but only websocket servers. It still doesn't explain why the WebSocket connection failed in the app...

**Comment by benzmuircroft** [comment]
Well I reasoned about it and came to the conclusion that I would be better off setting up my own switchboard on my server as you recommend doing that (https://github.com/rtc-io/rtc-switchboard) and also I would have 100% access to both sides of the picture so I recomend others to do the same as now it works fine!
