### ISSUE TITLE
Example crashes with 2 or more clients

### ISSUE THREAD

**Issue by garrows** [rtc-io/rtc-mesh#8]
Hi,
When I run the first example located at http://rtc.io/module-rtc-mesh.html it works on one machine. When I run another instance of the example the first one crashes. Restarting the first one will then crash the second one. 

```
vagrant@precise32:~/mesh$ node mesh.js
captured change key: "lastjoin" set to  1423632131800

/home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/rtc-tools/index.js:88
  return new PeerConnection(config, constraints);
         ^
TypeError: undefined is not a function
    at Object.exports.createConnection (/home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/rtc-tools/index.js:88:10)
    at connect (/home/vagrant/mesh/node_modules/rtc-quickconnect/index.js:277:14)
    at /home/vagrant/mesh/node_modules/rtc-quickconnect/index.js:524:5
    at /home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/mbus/index.js:42:22
    at Array.map (native)
    at bus (/home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/mbus/index.js:41:35)
    at /home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/rtc-signaller/handlers/announce.js:82:14
    at /home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/rtc-signaller/processor.js:101:11
    at loop (/home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/rtc-signaller/node_modules/pull-stream/sinks.js:15:33)
    at /home/vagrant/mesh/node_modules/rtc-quickconnect/node_modules/rtc-signaller/node_modules/pull-stream/throughs.js:126:7
```

**Comment by DamonOehlman** [comment]
Thanks Glen - I'll take a look and let you know...

**Comment by DamonOehlman** [comment]
Oh right, I see what is going on here, you are trying to run the demo from node.  Yeah, to do that you are going to need to use the [`rtc-plugin-node`](https://github.com/rtc-io/rtc-plugin-node) package.

There's some documentation on how to do this (not mesh specific, but I'm sure you'll work it out) in this repo:

https://github.com/rtc-io/demo-datachannel-node

Let me know how you go :)

**Comment by DamonOehlman** [comment]
@garrows How did you go getting this running under node?

**Comment by garrows** [comment]
I haven't had a chance to come back to it. Todo list is too long. Feel free
to close the issue if you want.

**Comment by DamonOehlman** [comment]
Cool mate - will do - feel free to hit me up if you have any questions.  I try to keep an eye on general questions at https://gitter.im/rtc-io/discuss these days too...
